spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379
#    password:
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: ${POSTS_ROUTE_URI:http://localhost:8080}
#          uri: ${POSTS_ROUTE_URI:lb://auth-server}
          predicates:
            - Path=/auth/**, /oauth2/authorize/**
          filters:
            - name: CustomOAuth2AuthorizationFilter
              args:
                authorities:
                  api/user/v5/account/manage: ROLE_admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

jwt: # Store token in a Volute
  secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1

server:
  port: 8085

authentication:
  enabled: false

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,*